<robot name="double-pendulum" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="depth" value="0.2"/>
  <xacro:property name="pole_radius" value="${depth / 8}"/>
  <xacro:property name="pole_length" value="0.8"/>
  <xacro:property name="pole_mass" value="0.5"/>
  <xacro:property name="cart_width" value="0.4"/>
  <xacro:property name="cart_height" value="${cart_width / 2}"/>
  <xacro:property name="cart_mass" value="8.0"/>
  <xacro:property name="elbow_radius" value="${depth / 4}"/>
  <xacro:property name="elbow_depth" value="${pole_radius * 6}"/>
  <xacro:property name="elbow_mass" value="0.1"/>

  <xacro:macro name="pole" params="name length radius mass">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
      </visual>
      <inertial>
	<mass value="${mass}"/>
	<inertia ixx="${mass * length * length / 3}" ixy="0.0" ixz="0.0"
		 iyy="0.0" iyz="0.0" izz="${mass * length * length / 3}"/>
      </inertial>
    </link>
  </xacro:macro>

  <xacro:macro name="null_inertia" params="">
    <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
  </xacro:macro>

  <link name="cart">
    <visual>
      <geometry>
        <box size="${cart_width} ${depth} ${cart_height}"/>
      </geometry>
    </visual>
    <inertial>
      <mass value="${cart_mass}"/>
      <xacro:null_inertia/>
    </inertial>
  </link>

  <xacro:pole name="pole1" length="${pole_length}" radius="${pole_radius}" mass="${pole_mass}"/>
  <xacro:pole name="pole2" length="${pole_length}" radius="${pole_radius}" mass="${pole_mass}"/>

  <link name="elbow">
    <visual>
      <geometry>
        <cylinder length="${elbow_depth}" radius="${elbow_radius}"/>
      </geometry>
    </visual>
    <inertial>
      <mass value="${elbow_mass}"/>
      <xacro:null_inertia/>
    </inertial>
  </link>

  <joint name="cart_to_pole" type="continuous">
    <axis xyz="0 1 0"/>
    <parent link="cart"/>
    <child link="pole1"/>
    <origin xyz="0 ${(depth + 2*pole_radius) / 2} ${pole_length / 2}"/>
  </joint>

  <joint name="pole_to_elbow" type="fixed">
    <origin rpy="${pi / 2} 0 0" xyz="0 ${elbow_depth / 3} ${(pole_length + elbow_radius) / 2}"/>
    <parent link="pole1"/>
    <child link="elbow"/>
  </joint>
  
  <joint name="elbow_to_pole" type="continuous">
    <axis xyz="0 1 0"/>
    <origin rpy="${pi/2} 0 0" xyz="0 ${pole_length / 2} ${-(elbow_depth/3)}"/>
    <parent link="elbow"/>
    <child link="pole2"/>
  </joint>
</robot>
